### PR TITLE
Fix some expected test data.

### PR DESCRIPTION
**Pull request by kfogel**
It looks like some test data originating in commit 6532f228 uses
"1663 Market St" for address to be looked up in the simulated browser
search, but then expects "1663 Market Street" in the corresponding
incident report.  As a result, Travis CI builds are failing -- see:

 https://github.com/redcross/arcdata/pull/58
 https://travis-ci.org/redcross/arcdata/builds/103004438
 https://travis-ci.org/redcross/arcdata/builds/103004459

### CODE REVIEW

**Comment by kfogel** [comment]
It's not clear to me whether the problem here is just an accidental mismatch between two parts of a test script, or a more serious failure of an address normalizer to expand "St" to "Street" in a context where it should do so.  If the latter, then this commit just papers over the real problem and instead of applying it we should find the right fix.

**Comment by OhMcGoo** [comment]
1663 Market St:

**Comment by kfogel** [comment]
Hey, @OhMcGoo, in your previous comment are you saying that this change is correct, i.e., we should expect "1663 Market St"  (and not "Street")?

If so, I'll merge this into master.  Flagging @jlaxson too, in case he has a chance to comment.

**Comment by OhMcGoo** [comment]
No, sorry to lead you astray. I was simply commenting that address is the office of the San Francisco Red Cross.

**Comment by frankduncan** [comment]
This test is apparently working on main, so I'm going to close this.

**Pull request closed without merging**
