### PR TITLE
Lessen number of log entries during updates.

### PR DESCRIPTION
**Pull request by bnazari**

### CODE REVIEW

**Comment by kfogel** [comment]
@bnazari, can you add a comment above the new conditional explaining why it's only logging every thousandth row now?  Someone who comes along in the future and sees that function will want to understand why it's written that way.

(I would have added "And if there's an issue ticket associated with the change, the comment should reference the ticket number.", but I looked and I don't think there's any corresponding issue.  If I'm wrong, though, please link to it.)

**Comment by kfogel** [comment]
I should have added: every PR should have a description explaining the motivation behind it.  The commits contained in the PR should mention the associated issue(s), if any, and the PR's description itself should mention them too.

This is really something that should go in a `CONTRIBUTING.md` file, and I will put it there soon.  But I noticed this PR didn't have a description, so I wanted to mention it here.

(Hope this all isn't coming off as too nit-picky, @bnazari!  The changes themselves are great; I just want to make sure they're accompanied by the information other contributors will need to understand them -- including myself in "other contributors".)

**Comment by bnazari** [comment]
Sorry I missed these comments. Been a crazy week for all of us! Anyway, I will be a bit more descriptive from now on! By the way, the reasoning for reducing the number of lines in the entry is due to the truncation of the errors for one of the regions. The error gets cut off and that really doesn't help with debugging.

**Comment by pjsier** [comment]
Thanks for the clarification, @bnazari! Do we want that clarification as a comment in the code before merging, @kfogel?

**Comment by jlaxson** [comment]
I would suggest taking a look at where this code is called from. There is already logic to control log rate I believe

**Comment by pjsier** [comment]
This update looks great @bnazari, @cecilia-donnelly @kfogel I can do a squash and merge of this if that works

**Comment by bnazari** [comment]
Awesome! Thank you. Hopefully we can see where the errors are happening soon. I suspect it is with xls2csv library, but I’m not certain yet. Might be some weird escape character that throws off the csv. This will definitely help shed some light to the matter!

**Comment by cecilia-donnelly** [comment]
@pjsier A squash would make this more readable, yes.  The new commit message should explain why we made this change (as always).  Thanks!

**Pull request merged**
