### PR TITLE
Display phone number in Incident's Case tab

### PR DESCRIPTION
**Pull request by OhMcGoo**

### CODE REVIEW

**Comment by kfogel** [comment]
I think the failing Travis CI tests above are unrelated to @OhMcGoo's commit 908f61dcb, and are instead due to the same thing that PR #59 fixes.  If so, then this commit can be merged (though of course it would be better to add a new test to make sure the phone number is displayed as expected now).

**Comment by frankduncan** [comment]
This was fixed long ago in some other place

**Comment by OhMcGoo** [comment]
I should have provided more detail. We want the Client's phone number to show up in the Client summary (under the Client's tab):
Client

**Comment by frankduncan** [comment]
Tested this and it's working as it's intended.  Merging and it should go into staging with the rest of the FY20 stuff.

**Pull request merged**
